server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/account_db
    username: alimurad
    password: alimurad05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  redis:
    host: localhost
    port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
