spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db
    username: tural
    password: tural05
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  redis:
    host: localhost
    port: 6380

  rabbitmq:
    host: localhost
    port: 5673
    username: alimurad
    password: alimurad05
