server:
  port: 8086

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/transfer_db
    username: alimurad
    password: alimurad05
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
